### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by Sunekaer** [MapperTV/embellishcraft#7]
Hi,

So with 1.14, forge created a folder called defaultconfigs, that modpacks makers should use to ship changed configs with, so the pack gets the right client, common and server config.
It takes the client and common files and puts them in the config folder and server files in the serverconfig folder.
So if I put embellishcraft-server.toml in defaultconfigs it places that file in serverconfig and my changed configs wont work as you are putting embellishcraft-server.toml in config.

Please change to use common or put the embellishcraft-server.toml in serverconfig folder

Regards
Sunekaer

**Comment by MapperTV** [comment]
My config registration is quite old and not 100% correct, this is something I need to rewrite.

**Comment by MapperTV** [comment]
I published a new update with the rewrite. Can you try and see if everything works as intended? Thanks.

**Comment by Sunekaer** [comment]
Looks good thanks!
