### ISSUE TITLE
Channels [embellishcraft:embellishcraft_channel] rejected their server side version number[MC-Version] Bug short description

### ISSUE THREAD

**Issue by SDUBZ** [MapperTV/embellishcraft#8]
forge: 1.14.4-107
EC: embellishcraft-1.14.4-1.4.0
logs:
client:
[latest.log](https://github.com/MapperTV/embellishcraft/files/4007478/latest.log)
server:
[debug.log](https://github.com/MapperTV/embellishcraft/files/4007479/debug.log)
[latest.log](https://github.com/MapperTV/embellishcraft/files/4007480/latest.log)

**Comment by MapperTV** [comment]
> [08:14:55] [Netty Client IO #1/ERROR]: Terminating connection with server, mismatched mod list

You seems to have a different mod list between your client and your server. Can you try to fix this problem first and see if this still happens?

**Comment by SDUBZ** [comment]
well there is mods removed because client mods

**Comment by MapperTV** [comment]
Client side mods shouldn't be a problem. On the server you seems to have remove many mods, maybe the client still has some. Btw the BoP add-on will work with the latest release.

**Comment by SDUBZ** [comment]
i updated i can connect again what ever is happening its affect the world or player

**Comment by MapperTV** [comment]
Please provide new logs so it will be easier to see.
